### ISSUE TITLE
How to change colors?

### ISSUE THREAD

**Issue by alpiua** [SiriusXT/trilium-theme-blue#1]
Thank you for the theme.
Obviously a dumb question, but I spent 20 minutes and couldn't figure out how I can change the background color for the note.
The white is too bright for me.
Also text color on tabs would be better if be darker.

**Comment by SiriusXT** [comment]
.body{
background-color: #eee;
}

**Comment by alpiua** [comment]
There is no such thing in the .css.
Where should I put it to have it working? 
Putting it in a random place and reloading the interface doesn't change anything.

**Comment by Checkerface230** [comment]
how do you change the color? where can I put that CSS .body because it seems it is not working I don't know why?

**Comment by SiriusXT** [comment]
css style add !important;
