### ISSUE TITLE
提个建议：将 /custom/ 改为 ../../../custom

### ISSUE THREAD

**Issue by Finish02** [SiriusXT/trilium-theme-blue#10]
部署在服务器上，如果访问 trilium url 是 https://abc.com/trilium，使用 /custom/ 的方式，背景图或字体路径就成了 https://abc.com/custom/background.png 这样子就找不到对应的文件了

**Comment by SiriusXT** [comment]
感谢提醒，已经修改

**Comment by Finish02** [comment]
感谢大佬做的好看的主题
