### ISSUE TITLE
样式的几点建议

### ISSUE THREAD

**Issue by szwss** [SiriusXT/trilium-theme-blue#11]
1. Title 的上下外边距放开一点,现在显得太拥挤了
2. 代码块的内边距现在基本没有,可以调大一些
3. 代码块 border 再来个圆角就更好了
4. 纯文字的行间距现在基本没有,可以调大一些
5. 引用的样式问题,引用中用了 code 标签,文字会看不见了

文档内容看着不拥挤才好些,行间距尽量大一点
请看下面参考图片

另外我尝试 import font-style.zip 报错引入不了

**Comment by szwss** [comment]
# 现在的间距
![图片](https://user-images.githubusercontent.com/584808/234916841-bba8c3c8-8bac-4c52-abbe-c1ba36a2a0b6.png)

# 期待的间距
![图片](https://user-images.githubusercontent.com/584808/234917255-f7050454-925b-4853-a5cb-1b7b2812cbf1.png)

# 引用的样式问题
![图片](https://user-images.githubusercontent.com/584808/234931122-100c2a6f-9c6d-4d52-a6e2-05efd48fbba3.png)

**Comment by SiriusXT** [comment]
35已经修改，
我尝试了font-style导入是没有出现问题的（没有勾选安全），你具体报什么错误，
关于124，感觉默认样式过于松散，特地让紧凑点，如果觉得拥挤可以去除样式中的包含margin，padding，line-height的行。

**Comment by szwss** [comment]
> 35已经修改， 我尝试了font-style导入是没有出现问题的（没有勾选安全），你具体报什么错误， 关于124，感觉默认样式过于松散，特地让紧凑点，如果觉得拥挤可以去除样式中的包含margin，padding，line-height的行。

trilium 是目前发布的最新版,
font-style导入,（没有勾选安全） 报错截图
![image](https://user-images.githubusercontent.com/584808/235044563-922c3841-712b-42a2-936f-01e822976c89.png)

![image](https://user-images.githubusercontent.com/584808/235042918-7f3a3693-3bc3-4070-b8d9-8bdf212c20c9.png)

**Comment by szwss** [comment]
padding 和 margin 都好多,不知道哪是哪,能否加上注释呀

**Comment by SiriusXT** [comment]
> trilium 是目前发布的最新版,

我在虚拟机里开了一个干净的trilium测试依然正常，不知道为啥你的为啥不行

**Comment by SiriusXT** [comment]
> padding 和 margin 都好多,不知道哪是哪,能否加上注释呀

都去掉就行，这些都是让更加紧凑的

**Comment by szwss** [comment]
我用了一个代码块高亮的 js 脚本
https://github.com/antoniotejada/Trilium-SyntaxHighlightWidget
目前代码块不能高亮,这是个这个编辑器缺陷,不知道还有没有更好的方案



> > padding 和 margin 都好多,不知道哪是哪,能否加上注释呀
> 
> 都去掉就行，这些都是让更加紧凑的

好的

**Comment by SiriusXT** [comment]
我根据那个改了一下，自己用的https://send.vis.ee/download/098ac28d0fe1ea5e/#Ltcmzg41XjE8NCsebBRqWw

**Comment by szwss** [comment]
谢谢 @SiriusXT

**Comment by Joackk** [comment]
> 我根据那个改了一下，自己用的https://send.vis.ee/download/098ac28d0fe1ea5e/#Ltcmzg41XjE8NCsebBRqWw

链接挂了，大佬补个档啊

**Comment by SiriusXT** [comment]
> 

[语法高亮.zip](https://github.com/SiriusXT/trilium-theme-blue/files/11365023/default.zip)

**Comment by Joackk** [comment]
> > 
> 
> [语法高亮.zip](https://github.com/SiriusXT/trilium-theme-blue/files/11365023/default.zip)

感谢

**Comment by Joackk** [comment]
> > 
> 
> [语法高亮.zip](https://github.com/SiriusXT/trilium-theme-blue/files/11365023/default.zip)

可以设置只读模式下也有语法高亮吗？似乎只有在编辑模式会有语法高亮，只读的话就没有效果了

**Comment by SiriusXT** [comment]
> > > 
> > 
> > 
> > [语法高亮.zip](https://github.com/SiriusXT/trilium-theme-blue/files/11365023/default.zip)
> 
> 可以设置只读模式下也有语法高亮吗？似乎只有在编辑模式会有语法高亮，只读的话就没有效果了
这我没有

**Comment by Joackk** [comment]
> > > > 
> > > 
> > > 
> > > [语法高亮.zip](https://github.com/SiriusXT/trilium-theme-blue/files/11365023/default.zip)
> > 
> > 
> > 可以设置只读模式下也有语法高亮吗？似乎只有在编辑模式会有语法高亮，只读的话就没有效果了
> > 这我没有

soga，大佬你写的另一个那个会记录浏览历史的插件触发条件是什么啊？我用了后，有三个被记录了，其他的都没有，是要特定条件才会触发吗？
