### ISSUE TITLE
关于有序列表的颜色问题

### ISSUE THREAD

**Issue by Joackk** [SiriusXT/trilium-theme-blue#12]
之前记得有序列表的颜色是和右边大纲是一样的，但是最近看的时候团然发现有序列表自从二级以后都用的一样的，没有三级四级了
比如我这里查看的三级列表的元素，结果他现是和二级一样的样式，以此类推往后面的都是这样
![image](https://user-images.githubusercontent.com/45162558/235383466-381c1cb2-4c9e-43cd-bdb9-4079d15fb6cc.png)
而大纲目录这边则是正常的
![image](https://user-images.githubusercontent.com/45162558/235383478-f6eab67f-1f3f-4909-97df-79a39aa46bef.png)
我以为是新版问题，所以又下了个老版本但是还是一样问题，主动给他加一个ol>会导致二级之后直接全部颜色控制没有了，该如何让有序列表继续和大纲同步呢？

**Comment by SiriusXT** [comment]
没有写过有序列表的颜色，如果想要可以添加
```
ol>li{
    color:var(--h2-background-color);
}
ol>li>ol>li{
    color:var(--h3-background-color);
}
ol>li>ol>li>ol>li{
    color:var(--h4-background-color);
}
ol>li>ol>li>ol>li>ol>li{
    color:var(--h5-background-color);
}
ol>li>ol>li>ol>li>ol>li>ol>li{
    color:var(--h6-background-color);
}
```

**Comment by Joackk** [comment]
> 没有写过有序列表的颜色，如果想要可以添加
> 
> ```
> ol>li{
>     color:var(--h2-background-color);
> }
> ol>li>ol>li{
>     color:var(--h3-background-color);
> }
> ol>li>ol>li>ol>li{
>     color:var(--h4-background-color);
> }
> ol>li>ol>li>ol>li>ol>li{
>     color:var(--h5-background-color);
> }
> ol>li>ol>li>ol>li>ol>li>ol>li{
>     color:var(--h6-background-color);
> }
> ```

我就是加入了这部分，但是从

> 没有写过有序列表的颜色，如果想要可以添加
> 
> ```
> ol>li{
>     color:var(--h2-background-color);
> }
> ol>li>ol>li{
>     color:var(--h3-background-color);
> }
> ol>li>ol>li>ol>li{
>     color:var(--h4-background-color);
> }
> ol>li>ol>li>ol>li>ol>li{
>     color:var(--h5-background-color);
> }
> ol>li>ol>li>ol>li>ol>li>ol>li{
>     color:var(--h6-background-color);
> }
> ```

感谢，我原本用的列表写法有是直接ol>li>li这样，用了大佬你给的改了一下后正常了
