### ISSUE TITLE
这个日历图标有点斜

### ISSUE THREAD

**Issue by zlxuan** [SiriusXT/trilium-theme-blue#15]
你好，这个日历图标是不是斜了一点，需要调整哪行代码呢
![Snipaste_2024-11-17_15-07-31](https://github.com/user-attachments/assets/b2202ff2-ebd5-468e-be12-c0a08d232eb4)

**Comment by SiriusXT** [comment]
我这边正常，你试试新的版本试试：
![图片](https://github.com/user-attachments/assets/11d122e6-a324-4aab-b168-de4f4fff3db1)

**Comment by zlxuan** [comment]
也不行，在我这儿就是斜的不知道为啥😭，web版也是斜的
我的版本是0.63.7

**Comment by SiriusXT** [comment]
我是0.90.11-beta了，你试试主题之前的版本

**Comment by zlxuan** [comment]
感谢您的解答，我也升级了，然后就没问题了，谢谢！
