### ISSUE TITLE
Ask for updates

### ISSUE THREAD

**Issue by star2k** [SiriusXT/trilium-theme-blue#2]
The new version does not display properly, it's time to update this theme

**Comment by SiriusXT** [comment]
![图片](https://user-images.githubusercontent.com/37627919/212245020-7ee9c126-510c-41f7-9dac-ec586e5f1e75.png)
After testing, it works well on version 0.58.4, please tell me where the display is abnormal.
![图片](https://user-images.githubusercontent.com/37627919/212245352-6a6bdc1e-9dd6-4ed2-ae18-805e004edebb.png)

**Comment by star2k** [comment]
> ![图片](https://user-images.githubusercontent.com/37627919/212245020-7ee9c126-510c-41f7-9dac-ec586e5f1e75.png) After testing, it works well on version 0.58.4, please tell me where the display is abnormal. ![图片](https://user-images.githubusercontent.com/37627919/212245352-6a6bdc1e-9dd6-4ed2-ae18-805e004edebb.png)

![222](https://user-images.githubusercontent.com/9582078/212245751-0c46c509-59c7-478b-8f29-d7c38b025e2f.png)

**Comment by star2k** [comment]
> > ![图片](https://user-images.githubusercontent.com/37627919/212245020-7ee9c126-510c-41f7-9dac-ec586e5f1e75.png) After testing, it works well on version 0.58.4, please tell me where the display is abnormal. ![图片](https://user-images.githubusercontent.com/37627919/212245352-6a6bdc1e-9dd6-4ed2-ae18-805e004edebb.png)
> 
> ![222](https://user-images.githubusercontent.com/9582078/212245751-0c46c509-59c7-478b-8f29-d7c38b025e2f.png)

https://github.com/Nriver/trilium-translation

**Comment by SiriusXT** [comment]
你主题用的最新的吗，我昨天刚更新的
![图片](https://user-images.githubusercontent.com/37627919/212247741-a72c9b48-7e15-4696-b37e-e9b26b7a2b76.png)

**Comment by star2k** [comment]
> 你主题用的最新的吗，我昨天刚更新的 ![图片](https://user-images.githubusercontent.com/37627919/212247741-a72c9b48-7e15-4696-b37e-e9b26b7a2b76.png)

原来如此，现在好了，
![89822D38AB234E4A2EC1836C3E79B89E](https://user-images.githubusercontent.com/9582078/212248309-fc19efb1-3fe1-4b20-84fe-817cc5e3ec36.png)
