### ISSUE TITLE
使用主题后，有些标题变白色，有些还是黑色是什么状况哇

### ISSUE THREAD

**Issue by Joackk** [SiriusXT/trilium-theme-blue#3]
就是用了大佬你的标题后，一小部分标题自动切成了白色，大部分还是黑色，这是什么状况啊？能自主修改吗？？
![image](https://user-images.githubusercontent.com/45162558/220037813-77f397fb-5987-402d-bb01-0a563384b967.png)

**Comment by Joackk** [comment]
已经找到了，是之前使用笔记设置的颜色也跟了过来导致的，作者大佬，这里标题的行距是哪个控制的啊？想要调整一下标题和文字的行距

**Comment by SiriusXT** [comment]
![图片](https://user-images.githubusercontent.com/37627919/220087964-1de30339-8092-46d9-884f-a3e83be15504.png)

**Comment by Joackk** [comment]
> ![图片](https://user-images.githubusercontent.com/37627919/220087964-1de30339-8092-46d9-884f-a3e83be15504.png)

margin-top这个是控制什么的哇？改了几下，但是没看出什么明显的改变

**Comment by SiriusXT** [comment]
![图片](https://user-images.githubusercontent.com/37627919/220112540-73560a68-b511-41f0-80d4-1d00657f707b.png)
margin-top是改标题和文字的行距，你说的标题是指log4j反序列化...这种小标题吗

**Comment by Joackk** [comment]
> ![图片](https://user-images.githubusercontent.com/37627919/220112540-73560a68-b511-41f0-80d4-1d00657f707b.png) margin-top是改标题和文字的距离，你说的标题是指log4j反序列表化...这种小标题吗

对，就是图中这个标题和文字的距离，我改top没发现明显变化，但是改了bottom感觉标题和文字距离拉开了

**Comment by Joackk** [comment]
> ![图片](https://user-images.githubusercontent.com/37627919/220112540-73560a68-b511-41f0-80d4-1d00657f707b.png) margin-top是修改标题和文字的距离，你说的标题是指log4j反序列表化...这种小标题吗

大标题是指的文章名字的那个标题吗？

**Comment by SiriusXT** [comment]
> > ![图片](https://user-images.githubusercontent.com/37627919/220112540-73560a68-b511-41f0-80d4-1d00657f707b.png) margin-top是修改标题和文字的距离，你说的标题是指log4j反序列表化...这种小标题吗
> 
> 大标题是指的文章名字的那个标题吗？

是的

**Comment by Joackk** [comment]
> > > ![图片](https://user-images.githubusercontent.com/37627919/220112540-73560a68-b511-41f0-80d4-1d00657f707b.png) margin-top是修改标题和文字的距离，你说的标题是指log4j反序列表化...这种小标题吗
> > 
> > 
> > 大标题是指的文章名字的那个标题吗？
> 
> 是的

大佬，请问控制目录字体的是那部分啊？就是右侧目录字体的，想要改小一点

**Comment by SiriusXT** [comment]
左侧目录？右侧目录？

**Comment by Joackk** [comment]
> 左侧目录？右侧目录？

右侧的目录，也叫大纲来着，不是左侧的，是每篇笔记里的那个目录

**Comment by SiriusXT** [comment]
添加：
div.toc-widget span.toc{
font-size: 10px;
}

**Comment by Joackk** [comment]
> 添加： div.toc-widget span.toc{ font-size: 10px; }

感谢大佬
