### ISSUE TITLE
目录可以设置当前所在吗？

### ISSUE THREAD

**Issue by Joackk** [SiriusXT/trilium-theme-blue#4]
比如我当前在这个目录下，可以设置这部分会加粗什么的吗？现在在哪部分都一样，有时候分不清自己在那一部分
![image](https://user-images.githubusercontent.com/45162558/224683213-ac304685-26af-466a-afea-217c03a4d705.png)

**Comment by SiriusXT** [comment]
这个暂时没法整，比较复杂

**Comment by Joackk** [comment]
> 这个暂时没法整，比较复杂

soga。感谢大佬。了解了

**Comment by SiriusXT** [comment]
粗糙实现了下：
https://github.com/SiriusXT/trilium-show-position-in-toc

**Comment by Joackk** [comment]
> 粗糙实现了下： https://github.com/SiriusXT/trilium-show-position-in-toc

tql大佬

**Comment by Joackk** [comment]
> 粗糙实现了下： https://github.com/SiriusXT/trilium-show-position-in-toc

对了大佬，请问你这个主题，代码的背景色设置是哪个啊？不是代码块的，是代码这部分的，我这边颜色设置的太淡了，不是很明显，想换个颜色，但是没找到在哪
![image](https://user-images.githubusercontent.com/45162558/225200280-5dacb669-dfc6-44ef-9245-b264c3804bbf.png)

**Comment by SiriusXT** [comment]
是哪部分

**Comment by Joackk** [comment]
> 是哪部分

这一部分，用`123`会变成代码部分的这个背景色是那个控制的哇？
![image](https://user-images.githubusercontent.com/45162558/225473357-2cfefab7-b651-4c19-a491-de08f2eeb524.png)

**Comment by SiriusXT** [comment]
.ck.ck-editor__editable .ck-code_selected {
  background-color: hsla(0,0%,78%,.5) !important;
}
.ck-content code {
  background-color: hsla(0,0%,78%,.3) !important;
}

**Comment by Joackk** [comment]
> .ck.ck-editor__editable .ck-code_selected { background-color: hsla(0,0%,78%,.5) !important; } .ck-content code { background-color: hsla(0,0%,78%,.3) !important; }

感谢大佬
