### ISSUE TITLE
如何设置代码颜色不影响代码块中颜色

### ISSUE THREAD

**Issue by Joackk** [SiriusXT/trilium-theme-blue#5]
按照前面大佬说的设置后，编辑模式不会影响，这部分会让代码块中的代码部分也套一层颜色，这部分该如何设置让他不影响代码块中的颜色？
当我启用这部分的时候
![image](https://user-images.githubusercontent.com/45162558/225493203-b901a1ca-547d-4c14-a00f-65d282e6d3a8.png)
代码块中的颜色也会受到影响
![image](https://user-images.githubusercontent.com/45162558/225493285-7ca93b54-3e45-4e19-9b5b-1e8080f6ac34.png)
该怎么设置才能避免他不会影响代码块中的颜色呢？

**Comment by SiriusXT** [comment]
改这个
.ck.ck-editor__editable .ck-code_selected {
  background-color: #111 !important;
}

**Comment by Joackk** [comment]
> 改这个 .ck.ck-editor__editable .ck-code_selected { background-color: #111 !important; }

好像不太行？
![image](https://user-images.githubusercontent.com/45162558/225498529-beff33ea-777f-43b1-a649-ed8b327a75bb.png)
![image](https://user-images.githubusercontent.com/45162558/225498582-415cd2ec-8a69-4765-93b4-4239eff3230c.png)

删掉.ck-content code这部分倒是可以，但是背景色只有在编辑的时候才会加深，浏览时候颜色依旧变

**Comment by SiriusXT** [comment]
> > 改这个 .ck.ck-editor__editable .ck-code_selected { background-color: #111 !important; }
> 
> 好像不太行？ ![image](https://user-images.githubusercontent.com/45162558/225498529-beff33ea-777f-43b1-a649-ed8b327a75bb.png) ![image](https://user-images.githubusercontent.com/45162558/225498582-415cd2ec-8a69-4765-93b4-4239eff3230c.png)
> 
> 删掉.ck-content code这部分倒是可以，但是背景色只有在编辑的时候才会加深，浏览时候颜色依旧变

![图片](https://user-images.githubusercontent.com/37627919/225530895-1efba502-2278-4f82-a8a2-0d063ca982b6.png)
![图片](https://user-images.githubusercontent.com/37627919/225530929-bfbeea04-5a62-48e1-93fc-0fc831b137d1.png)
在只读模式下，代码和代码块的渲染差不多，一样的，改.ck-content code

**Comment by Joackk** [comment]
> > > 改这个 .ck.ck-editor__editable .ck-code_selected { background-color: #111 !important; }
> > 
> > 
> > 好像不太行？ ![image](https://user-images.githubusercontent.com/45162558/225498529-beff33ea-777f-43b1-a649-ed8b327a75bb.png) ![image](https://user-images.githubusercontent.com/45162558/225498582-415cd2ec-8a69-4765-93b4-4239eff3230c.png)
> > 删掉.ck-content code这部分倒是可以，但是背景色只有在编辑的时候才会加深，浏览时候颜色依旧变
> 
> ![图片](https://user-images.githubusercontent.com/37627919/225530895-1efba502-2278-4f82-a8a2-0d063ca982b6.png) ![图片](https://user-images.githubusercontent.com/37627919/225530929-bfbeea04-5a62-48e1-93fc-0fc831b137d1.png) 在只读模式下，代码和代码块的渲染差不多，一样的，改.ck-content code

感谢大佬，我去掉了!important后，他就不会影响代码块中的颜色了

**Comment by szwss** [comment]
> 按照前面大佬说的设置后，编辑模式不会影响，这部分会让代码块中的代码部分也套一层颜色，这部分该如何设置让他不影响代码块中的颜色？ 当我启用这部分的时候 ![image](https://user-images.githubusercontent.com/45162558/225493203-b901a1ca-547d-4c14-a00f-65d282e6d3a8.png) 代码块中的颜色也会受到影响 ![image](https://user-images.githubusercontent.com/45162558/225493285-7ca93b54-3e45-4e19-9b5b-1e8080f6ac34.png) 该怎么设置才能避免他不会影响代码块中的颜色呢？

您的代码块能有颜色?
是用的这个方案吗?
https://github.com/antoniotejada/Trilium-SyntaxHighlightWidget
我感觉不好用,编辑器仅有的缺陷,

如果不是,可以看看用的哪个方案吗?

**Comment by SiriusXT** [comment]
![图片](https://user-images.githubusercontent.com/37627919/235036708-5e13817e-5620-4f69-a06c-8247287eed21.png)
这个改成
note-detail-code code试试

**Comment by Joackk** [comment]
> > 按照前面大佬说的设置后，编辑模式不会影响，这部分会让代码块中的代码部分也套一层颜色，这部分该如何设置让他不影响代码块中的颜色？ 当我启用这部分的时候 ![image](https://user-images.githubusercontent.com/45162558/225493203-b901a1ca-547d-4c14-a00f-65d282e6d3a8.png) 代码块中的颜色也会受到影响 ![image](https://user-images.githubusercontent.com/45162558/225493285-7ca93b54-3e45-4e19-9b5b-1e8080f6ac34.png) 该怎么设置才能避免他不会影响代码块中的颜色呢？
> 
> 您的代码块能有颜色? 是用的这个方案吗? https://github.com/antoniotejada/Trilium-SyntaxHighlightWidget 我感觉不好用,编辑器仅有的缺陷,
> 
> 如果不是,可以看看用的哪个方案吗?

你说的代码块能有颜色是指那部分？是``这样标注的代码块，还是```的代码块？颜色是语法高亮的意思吗？
