### ISSUE TITLE
右侧目录的边距调整该如何设置？

### ISSUE THREAD

**Issue by Joackk** [SiriusXT/trilium-theme-blue#6]
大佬这里我看F12的标签是这样的
![image](https://user-images.githubusercontent.com/45162558/227531535-fd61b017-341b-4716-a424-8c777ccc7601.png)
但是我把这部分加入到主题里却并没有效果，这是为何？我看其他的标签基本都是对应的，该如何让他生效呢？
![image](https://user-images.githubusercontent.com/45162558/227531709-7a025da2-5721-487d-a3a1-fd20dc585a63.png)

**Comment by SiriusXT** [comment]
去掉>

**Comment by Joackk** [comment]
> 去掉>

去掉后，似乎也没有反应，是要加上这边的class名称吗？我用div#xxxx这样加上去也没效果
![image](https://user-images.githubusercontent.com/45162558/227663371-20805398-5d00-4421-8be6-257d2688f9d4.png)

**Comment by SiriusXT** [comment]
我改这个有变化，是不是变化太小了看不出来，再不行改成 5px !important;

**Comment by Joackk** [comment]
> 我改这个有变化，是不是变化太小了看不出来，再不行改成 5px !important;

加上!important后可以了，没加的时候似乎是优先级不够，感谢大佬
