### ISSUE TITLE
Left Blue Panel Colour is Inconsistent 

### ISSUE THREAD

**Issue by 905jay** [SiriusXT/trilium-theme-blue#7]
Hello

First of all thanks for this theme, once I get this issue sorted I think it will be the best theme yet!
On the blue panel to the far left, the Trilium logo is colored fine with the blue background, however the New Note, Search, Jump to note, Global Note Map, Show Recent Changes, Calendar are all with a non-blue background. 

Same with the Protected Session, Sync and Hide Panel. 

The rest of the panel element is blue.

I downloaded background.png and added this as an owned attribute 
#originalFileName=background.png #customResourceProvider=background.png

![2023-04-12 08 32 45](https://user-images.githubusercontent.com/13971036/231459734-cdec2951-cee6-4391-930f-02b56ef505d2.png)

**Comment by SiriusXT** [comment]
Your trilium version does not correspond to the theme version. A simple solution is to update both trilium and blue-theme to the latest. Or find the historical version of blue-theme from the following link：
https://github.com/SiriusXT/trilium-theme-blue/commits/main

**Comment by 905jay** [comment]
You're spot on, thanks kindly for responding. I realized that an hour ago,
and was going to close the issue I created. My apologies, I didn't realize
I had an old version tagged in my docker.

Thanks this theme is beautiful



---
This email was sent from a Google Pixel 7 Pro. Please excuse spelling
and/or errors in grammar.

**Comment by 905jay** [comment]
I had a version tag for my trillium container that was older, and incompatible with the theme. Issue was on my end.
Now that I have fully updated my Trilium Notes container to latest version, issue is resolved.
