### ISSUE TITLE
启动栏书签图标位置不对

### ISSUE THREAD

**Issue by Finish02** [SiriusXT/trilium-theme-blue#8]
大佬，使用主题后，启动栏书签图标位置不对，如图：
![图片](https://user-images.githubusercontent.com/50348289/234734172-1be2c721-1f17-4c98-ada0-f47cc7a9d1fd.png)
请问要怎么解决？

**Comment by SiriusXT** [comment]
我试了下是正常的，你是不是trilium或主题不是最新的
![图片](https://user-images.githubusercontent.com/37627919/234746005-3a04af28-c55a-4bd5-8e25-f021331a9a84.png)

**Comment by Finish02** [comment]
给书签添加 #bookmarkFolder  属性后就会这样子

**Comment by SiriusXT** [comment]
已经修复，更新主题试试

**Comment by Finish02** [comment]
正常了，谢谢大佬
