### ISSUE TITLE
链接缩进

### ISSUE THREAD

**Issue by daomengRen** [SiriusXT/trilium-theme-blue#9]
大佬，使用主题后，发现链接也会有缩进，强迫症想关闭，求大佬赐教
![image](https://user-images.githubusercontent.com/46952617/234747727-47e0f974-9620-4a9a-8c9b-20e81ed3a233.png)

**Comment by SiriusXT** [comment]
已经修复，更新主题试试

**Comment by daomengRen** [comment]
谢谢大佬，完美了
